# Generated by Django 4.1.2 on 2022-10-28 10:04

from django.db import migrations, models
import phone_field.models
import signup.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email Address')),
                ('password', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=signup.models.get_file_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=signup.models.get_file_path)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True)),
            ],
        ),
    ]
