# Generated by Django 4.1.2 on 2022-10-28 13:19

from django.db import migrations, models
import phone_field.models
import signup.models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='approval',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email Address')),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='organizations',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email Address')),
                ('password', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('image1', models.ImageField(upload_to=signup.models.get_file_path)),
                ('image2', models.ImageField(upload_to=signup.models.get_file_path)),
                ('location', models.CharField(max_length=200)),
                ('contact', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='users',
            name='description',
        ),
        migrations.RemoveField(
            model_name='users',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='users',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='users',
            name='location',
        ),
    ]
